services:
  app:
    container_name: test-devops-app
    build:
      context: .
    environment:
      PORT: 3000
      NODE_ENV: local
      ENABLE_METRICS: "true"
      SERVICE_NAME: "test-devops"
      DD_AGENT_HOST: datadog-agent
      DD_DOGSTATSD_PORT: "8125"
    depends_on:
      - datadog-agent
    ports:
      - "3000:3000"

  datadog-agent:
    container_name: datadog-agent
    image: gcr.io/datadoghq/agent:latest
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_SITE=datadoghq.com
      - DD_ENV=local
      - DD_HOSTNAME=local-dev
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
      - DD_DOGSTATSD_PORT=8125
      - DD_LOGS_ENABLED=true
      - DD_APM_ENABLED=true
      - DD_PROCESS_AGENT_ENABLED=true
    ports:
      - "8125:8125/udp"
      - "8126:8126/tcp"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
