services:
  app:
    container_name: test-devops-app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    environment:
      NODE_ENV: development
      PORT: 3000
      STATSD_HOST: graphite
      STATSD_PORT: 8125
    ports:
      - "3000:3000"
    depends_on:
      - graphite
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:3000/healthz || exit 1" ]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - local-test-devops-network

  graphite:
    image: graphiteapp/graphite-statsd:latest
    container_name: graphite
    restart: unless-stopped
    ports:
      - "8080:80"
      - "8125:8125/udp"
      - "8126:8126"
    volumes:
      - local-graphite-data:/opt/graphite/storage
    networks:
      - local-test-devops-network

volumes:
  local-graphite-data:

networks:
  local-test-devops-network: