apiVersion: v1
kind: Service
metadata:
  name: test-devops-app
  labels:
    app: {{ include "test-devops.name" . }}
  annotations:
    cloud.google.com/backend-config: '{"ports": {"80": "test-devops-backend-config"}}'
spec:
  type: LoadBalancer
  selector:
    app: {{ include "test-devops.name" . }}
    component: app
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.app.port }}
      protocol: TCP
