{{- if .Values.datadog.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "test-devops.fullname" . }}-datadog
  labels:
    {{- include "test-devops.labels" . | nindent 4 }}
    app: datadog-agent
{{- end }}

