{{- if .Values.datadog.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "test-devops.fullname" . }}-datadog-secret
  labels:
    {{- include "test-devops.labels" . | nindent 4 }}
    app: datadog-agent
type: Opaque
data:
  {{- if .Values.datadog.apiKey }}
  api-key: {{ .Values.datadog.apiKey | b64enc | quote }}
  {{- else }}
  api-key: ""
  {{- end }}
{{- end }}

