{{- if .Values.graphite.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphite
spec:
  replicas: {{ .Values.graphite.replicaCount }}
  selector:
    matchLabels:
      app: graphite
  template:
    metadata:
      labels:
        app: graphite
    spec:
      containers:
        - name: graphite
          image: graphiteapp/graphite-statsd:latest
          ports:
            - name: http
              containerPort: 80
            - name: statsd-udp
              containerPort: 8125
              protocol: UDP
            - name: car-admin
              containerPort: 8126
          volumeMounts:
            - name: graphite-storage
              mountPath: /opt/graphite/storage
      volumes:
        - name: graphite-storage
          persistentVolumeClaim:
            claimName: graphite-pvc
{{- end }}
