{{- if .Values.prometheus.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "test-devops.fullname" . }}
  labels:
    {{- include "test-devops.labels" . | nindent 4 }}
    {{- with .Values.prometheus.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "test-devops.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: http
    path: {{ .Values.prometheus.serviceMonitor.path }}
    interval: {{ .Values.prometheus.serviceMonitor.interval }}
    scrapeTimeout: {{ .Values.prometheus.serviceMonitor.scrapeTimeout }}
{{- end }}
