{{- if and .Values.vault.enabled .Values.vault.secrets.secretPath }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-vault-{{ .Values.vault.secrets.secretPath | replace "/" "-" | lower }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: vault-secret
stringData:
{{- range $key, $env := .Values.vault.secrets.fields }}
  {{ $env | lower }}: "<vault-value-placeholder>"
{{- end }}
{{- end }}

