{{- if .Values.graphite.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: graphite
spec:
  type: ClusterIP
  selector:
    app: graphite
  ports:
    - name: http
      port: 8080
      targetPort: 80
    - name: statsd-udp
      port: 8125
      targetPort: 8125
      protocol: UDP
{{- end }}
